const QUIZ_DATA = {
    topics: [
        { id: 'fundamentals', name: 'Testing Fundamentals', icon: '📘', questions: [] },
        { id: 'stlc', name: 'STLC', icon: '🔄', questions: [] },
        { id: 'levels', name: 'Level of Testing', icon: '📊', questions: [] },
        { id: 'types', name: 'Types of Testing', icon: '🧪', questions: [] },
        { id: 'quality', name: 'Software Quality', icon: '⭐', questions: [] },
        { id: 'planning', name: 'Test Planning', icon: '📋', questions: [] },
        { id: 'management', name: 'Test Management', icon: '📁', questions: [] },
        { id: 'testcases', name: 'Test Cases', icon: '📝', questions: [] },
        { id: 'bugreport', name: 'Bug Report', icon: '🐛', questions: [] },
        { id: 'approaches', name: 'Test Approaches', icon: '🎯', questions: [] },
        { id: 'domain', name: 'Domain Testing', icon: '🔢', questions: [] },
        { id: 'decision', name: 'Decision Table Testing', icon: '📐', questions: [] },
        { id: 'state', name: 'State Transition Testing', icon: '🔀', questions: [] },
        { id: 'usecase', name: 'Use Case Testing', icon: '👤', questions: [] },
        { id: 'gui', name: 'GUI Testing', icon: '🖥️', questions: [] },
        { id: 'security', name: 'Security Testing', icon: '🔐', questions: [] },
        { id: 'api', name: 'API Testing', icon: '🌐', questions: [] },
        { id: 'database', name: 'Database Testing', icon: '🗄️', questions: [] },
        { id: 'whitebox', name: 'White Box Testing', icon: '⚙️', questions: [] },
        { id: 'automation', name: 'Automation Testing', icon: '🤖', questions: [] }
    ]
};

// 1. Testing Fundamentals (10 câu - Q1-10 section 1)
QUIZ_DATA.topics[0].questions = [
    { q: "Which testing level focuses on the overall system integration?", opts: ["Unit testing", "Regression testing", "Acceptance testing", "Integration testing"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Integration Testing</b><br>Integration Testing (Kiểm thử tích hợp) là cấp độ kiểm thử tập trung vào việc verified sự tương tác, giao tiếp và truyền dữ liệu giữa các module hoặc thành phần hệ thống khi chúng được kết hợp với nhau.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Unit Testing:</b> Kiểm thử mức thấp nhất, tập trung vào từng đơn vị riêng lẻ (hàm, phương thức) một cách cô lập (isolated), chưa quan tâm đến việc chúng tương tác với nhau.<br>❌ <b>B. Regression Testing:</b> Đây là LOẠI kiểm thử (test type) thực hiện khi có thay đổi code để đảm bảo không phát sinh lỗi mới, không phải là một LEVEL kiểm thử cụ thể.<br>❌ <b>C. Acceptance Testing:</b> Cấp độ kiểm thử cao nhất, xác nhận hệ thống có thỏa mãn yêu cầu nghiệp vụ và user needs hay không, không tập trung vào kỹ thuật tích hợp module." },
    { q: "What is the difference between static testing and dynamic testing?", opts: ["Static testing is performed by developers, dynamic testing by testers", "Static testing is performed before coding, dynamic testing after coding", "Static testing involves executing code, dynamic testing involves reviewing code", "There is no difference"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Static trước coding, Dynamic sau coding (theo cách hiểu thông thường)</b><br>Theo chuẩn ISTQB chính xác:<br>- <b>Static Testing:</b> Kiểm tra tài liệu (Requirement, Design) hoặc Review Code mà KHÔNG chạy chương trình. (Phần Review Requirements làm TRƯỚC coding, phần Review Code làm trong/sau coding).<br>- <b>Dynamic Testing:</b> Bắt buộc phải CHẠY chương trình.<br>Trong ngữ cảnh câu hỏi này, đáp án B là hợp lý nhất để phân biệt thời điểm bắt đầu sớm nhất.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Cả Dev và Tester đều làm được cả hai.<br>❌ <b>C:</b> Ngược lại mới đúng.<br>❌ <b>D:</b> Khác biệt rõ ràng về Execution." },
    { q: "What is software testing?", opts: ["The process of creating software", "The process of maintaining software", "The process of designing software", "The process of finding bugs in software"], ans: 3, exp: "<b>✅ Đáp án đúng là D: The process of finding bugs</b><br>Mục tiêu cốt lõi của Software Testing là thực thi chương trình với ý định tìm ra lỗi (defects/bugs) để đảm bảo chất lượng phần mềm trước khi đến tay người dùng.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Creating software:</b> Đây là định nghĩa của Development (Coding/Programming).<br>❌ <b>B. Maintaining software:</b> Đây là giai đoạn Maintenance (bảo trì) trong SDLC.<br>❌ <b>C. Designing software:</b> Đây là giai đoạn Design (thiết kế kiến trúc/UI) trong SDLC." },
    { q: "What is the main purpose of a test case?", opts: ["To design the user interface", "To document the dev process", "To identify defects in software", "To outline the project schedule"], ans: 2, exp: "<b>✅ Đáp án đúng là C: To identify defects in software</b><br>Test Case (Trường hợp kiểm thử) là tập hợp các điều kiện, inputs, steps và expected results được thiết kế cụ thể để kiểm tra một chức năng, nhằm mục đích TÌM LỖI nếu phần mềm hoạt động không đúng mong đợi.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Design UI:</b> Nhiệm vụ của UI/UX Designer.<br>❌ <b>B. Document dev process:</b> Nhiệm vụ của Technical Writer hoặc Developer documentation.<br>❌ <b>D. Project schedule:</b> Nhiệm vụ của Project Manager trong Project Plan." },
    { q: "What is the significance of automated testing?", opts: ["It can perform tests difficult for humans", "It is faster than manual testing", "It is more accurate and repeatable", "All of the above"], ans: 3, exp: "<b>✅ Đáp án đúng là D: All of the above</b><br>Automated Testing mang lại nhiều lợi ích vượt trội:<br>1. <b>Perform difficult tests:</b> Test tải (Load/Stress) với hàng nghìn user ảo mà con người không thể làm thủ công.<br>2. <b>Faster:</b> Máy chạy script nhanh hơn nhiều so với người thao tác click chuột.<br>3. <b>Accurate & Repeatable:</b> Máy không biết mệt, không lơ là, chạy 1000 lần y hệt nhau (consistancy), tránh lỗi human error." },
    { q: "Which testing phase helps ensure software works correctly after changes?", opts: ["Regression testing", "Performance testing", "Unit testing", "System testing"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Regression Testing</b><br>Regression Testing (Kiểm thử hồi quy) được thực hiện SAU KHI CÓ THAY ĐỔI (sửa bug, thêm tính năng) để đảm bảo rằng những thay đổi đó KHÔNG làm hỏng các chức năng đang hoạt động tốt trước đó.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Performance Testing:</b> Đo lường tốc độ, độ ổn định, không phải tính đúng đắn chức năng sau thay đổi.<br>❌ <b>C. Unit Testing:</b> Kiểm tra đơn vị code lẻ, không đảm bảo toàn hệ thống work correctly sau change.<br>❌ <b>D. System Testing:</b> Kiểm tra toàn bộ hệ thống theo requirement, nhưng không mang ý nghĩa đặc thù là 'check after changes' như Regression." },
    { q: "What is the role of a test plan in software testing?", opts: ["To document overall testing strategy", "To specify features to include", "To outline coding standards", "To provide release schedule"], ans: 0, exp: "<b>✅ Đáp án đúng là A: To document overall testing strategy</b><br>Test Plan là tài liệu sườn sống, định nghĩa CHIẾN LƯỢC kiểm thử: Scope (phạm vi), Objectives (mục tiêu), Resources (nhân lực/tool), Schedule (lịch trình) và Approach (cách tiếp cận).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Specify features:</b> Đây là nhiệm vụ của Requirements Specification (SRS/PRD).<br>❌ <b>C. Outline coding standards:</b> Đây là Coding Convention/Guidelines của Dev.<br>❌ <b>D. Provide release schedule:</b> Đây là Release Plan (dù Test Plan có nhắc đến schedule test, nhưng không phải main purpose là release schedule)." },
    { q: "When should testing activities ideally begin in the SDLC?", opts: ["Before design phase", "During requirements gathering", "After coding is complete", "Only after deployment"], ans: 1, exp: "<b>✅ Đáp án đúng là B: During requirements gathering</b><br>Theo nguyên lý 'Early Testing' (Kiểm thử sớm), testing nên bắt đầu ngay từ giai đoạn lấy yêu cầu. Tester review requirements để tìm lỗi logic/thiếu sót ngay trên giấy. Lỗi phát hiện càng sớm, chi phí sửa càng thấp.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Before design:</b> Requirements IS before design, so A is implicitly similar but 'During requirements' cụ thể và chuẩn xác hơn.<br>❌ <b>C. After coding:</b> Cách làm truyền thống (Waterfall) cũ, rủi ro cao, tốn kém chi phí fix bug.<br>❌ <b>D. After deployment:</b> Quá trễ, lỗi đã đến tay người dùng (Production issue)." },
    { q: "What is the purpose of usability testing?", opts: ["Check performance under stress", "Ensure handling many users", "Verify business requirements", "Evaluate UI and user experience"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Evaluate UI and user experience</b><br>Usability Testing đánh giá mức độ DỄ SỬ DỤNG, trực quan, và trải nghiệm người dùng (UX) của phần mềm. Mục tiêu là xem user có dễ dàng hoàn thành task không.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Check performance under stress:</b> Đây là Stress Testing.<br>❌ <b>B. Handling many users:</b> Đây là Load Testing.<br>❌ <b>C. Verify business requirements:</b> Đây là User Acceptance Testing (UAT)." },
    { q: "Which is NOT a primary goal of software testing?", opts: ["Maximizing dev team's coding speed", "Ensuring software meets requirements", "Ensuring software is reliable", "Finding defects"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Maximizing dev team's coding speed</b><br>Testing thường làm... CHẬM tốc độ release (ngắn hạn) vì phải dừng lại để fix bug. Mục tiêu của Test team KHÔNG PHẢI là giúp Dev code nhanh hơn, mà là đảm bảo chất lượng.<br><br><b>Tại sao các đáp án khác sai?</b><br>✅ <b>B, C, D</b> ĐỀU LÀ MỤC TIÊU của Testing:<br>- Đáp ứng yêu cầu (Validation)<br>- Đảm bảo độ tin cậy (Reliability)<br>- Tìm lỗi (Defect detection)" }
];

// 2. STLC (10 câu - Q11-20 section 1)
QUIZ_DATA.topics[1].questions = [
    { q: "What is the first phase in the Software Testing Life Cycle (STLC)?", opts: ["Test Execution", "Test Planning", "Test Closure", "Test Design"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Test Planning</b><br>Test Planning (Lập kế hoạch kiểm thử) là bước đầu tiên trong số các lựa chọn này. Nó xác định CHIẾN LƯỢC kiểm thử, phạm vi (scope), tài nguyên (resources), và lịch trình (schedule).<br><i>Lưu ý: Một số tài liệu liệt kê 'Requirement Analysis' là bước đầu tiên, sau đó đến Planning.</i><br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Test Execution:</b> Giai đoạn thực thi (chạy test), diễn ra sau Planning và Design.<br>❌ <b>C. Test Closure:</b> Giai đoạn đóng dự án, diễn ra cuối cùng.<br>❌ <b>D. Test Design:</b> Giai đoạn thiết kế test case, diễn ra SAU khi đã có Plan." },
    { q: "What is the purpose of the Test Execution phase?", opts: ["To analyze test results", "To close testing activities", "To execute test cases", "To plan testing activities"], ans: 2, exp: "<b>✅ Đáp án đúng là C: To execute test cases</b><br>Test Execution là giai đoạn 'hành động': Tester chạy script, nhập dữ liệu, và HOẠT ĐỘNG trên phần mềm để tìm lỗi. Kết quả Pass/Fail được ghi lại tại đây.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Analyze test results:</b> Việc phân tích là một phần của reporting, không phải mục đích chính của Execution phase.<br>❌ <b>B. Close testing activities:</b> Đây là mục đích của Test Closure.<br>❌ <b>D. Plan testing activities:</b> Đây là mục đích của Test Planning." },
    { q: "In which phase are test scripts and test data prepared?", opts: ["Test Execution", "Test Design", "Test Planning", "Test Closure"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Test Design</b><br>Trong các lựa chọn này, Test Design là giai đoạn phù hợp nhất (dù theo ISTQB chi tiết, việc tạo script/data cụ thể thuộc về phase <b>Test Implementation</b>).<br>- <b>Test Design:</b> Xác định 'Test cái gì' (Conditions) và 'Test như thế nào' (High level cases).<br>- <b>Test Implementation:</b> Chuẩn bị 'Cái gì để test' (Data, Scripts, Environment).<br>Do không có đáp án Implementation, ta chọn Design (giai đoạn liền kề).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> Quá trễ.<br>❌ <b>C:</b> Quá sớm." },
    { q: "During which phase are test cases developed based on requirements?", opts: ["Test Closure", "Test Design", "Test Planning", "Test Execution"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Test Design</b><br>Test Design là quá trình chuyển đổi Requirements -> Test Scenarios -> Test Cases cụ thể. Output chính của giai đoạn này là bộ Test Case hoàn chỉnh.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Test Closure:</b> Đã xong, không phát triển thêm.<br>❌ <b>C. Test Planning:</b> Lên kế hoạch tổng thể.<br>❌ <b>D. Test Execution:</b> Thực hiện theo test case đã có." },
    { q: "When is the actual testing of the software carried out?", opts: ["Test Closure", "Test Design", "Test Execution", "Test Planning"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Test Execution</b><br>Đây là lúc phần mềm thực sự được KIỂM TRA (exercised). Tester tương tác với ứng dụng, API, database để xác minh hành vi của nó.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Các giai đoạn này liên quan đến giấy tờ, kế hoạch, thiết kế, tổng kết - không trực tiếp chạy phần mềm để tìm lỗi." },
    { q: "Which phase involves comparing actual results with expected results?", opts: ["Test Planning", "Test Closure", "Test Execution", "Test Design"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Test Execution</b><br>Đây là hoạt động cốt lõi của việc chạy test: So sánh Thực tế (Actual) vs Kỳ vọng (Expected). Nếu khác nhau -> Có Bug.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Test Planning:</b> Chưa có kết quả thực tế.<br>❌ <b>B. Test Closure:</b> Chỉ tổng hợp kết quả đã so sánh.<br>❌ <b>D. Test Design:</b> Mới chỉ định nghĩa Expected Result, chưa có Actual Result." },
    { q: "What is the primary goal of the Test Closure phase?", opts: ["To close defects", "To formally close testing activities", "To design test cases", "To execute test cases"], ans: 1, exp: "<b>✅ Đáp án đúng là B: To formally close testing activities</b><br>Test Closure đánh dấu sự HOÀN THÀNH chính thức. Nó bao gồm việc nghiệm thu (Sign-off), lưu trữ tài liệu (Archiving), và họp rút kinh nghiệm (Retrospective).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. To close defects:</b> Defects được close trong quá trình Execution/Bug Fixing cycle.<br>❌ <b>C. Design test cases:</b> Thuộc Test Design.<br>❌ <b>D. Execute test cases:</b> Thuộc Test Execution." },
    { q: "Which phase ensures all test deliverables are finalized and archived?", opts: ["Test Design", "Test Planning", "Test Execution", "Test Closure"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Test Closure</b><br>Một trong những tasks quan trọng nhất của Test Closure là 'Archiving': Đảm bảo Test Plans, Cases, Reports, Logs được lưu trữ đầy đủ để tham chiếu sau này hoặc tái sử dụng (Regression).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Lúc này các deliverables đang được TẠO RA hoặc CẬP NHẬT, chưa phải lúc finalize/archive." },
    { q: "Which phase involves summarizing testing and preparing summary report?", opts: ["Test Planning", "Test Execution", "Test Design", "Test Closure"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Test Closure</b><br>Test Summary Report là output cuối cùng, tổng hợp metrics: Bao nhiêu case pass/fail? Có bao nhiêu bug critical? Code coverage bao nhiêu? Ready to release chưa?<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Planning:</b> Tạo Test Plan, không phải Summary Report.<br>❌ <b>B. Execution:</b> Tạo Bug Report/Status Report hàng ngày.<br>❌ <b>C. Design:</b> Tạo Test Case Specification." },
    { q: "Which phase involves defining scope, objectives, resources, and schedule?", opts: ["Test Closure", "Test Execution", "Test Design", "Test Planning"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Test Planning</b><br>Đây là định nghĩa kinh điển của Test Planning: Xác định Scope (Phạm vi test cái gì/không test cái gì), Objective (Mục tiêu), Resources (Con người, server, tool) và Schedule (Timeline).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Đều là các bước thực hiện chi tiết SAU khi Plan đã được duyệt." }
];

// 3. Level of Testing (10 câu - Q21-30 section 1)
QUIZ_DATA.topics[2].questions = [
    { q: "Which test level is concerned with security, performance, and usability defects?", opts: ["Acceptance Testing", "Functional Testing", "Non-Functional Testing", "Regression Testing"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Non-Functional Testing</b><br>Non-Functional Testing kiểm tra các thuộc tính CHẤT LƯỢNG (Quality Attributes) của hệ thống thay vì chức năng nghiệp vụ. Ví dụ: Security (Bảo mật), Performance (Hiệu năng), Usability (Tính khả dụng).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Acceptance Testing:</b> Tập trung vào business needs và user acceptance.<br>❌ <b>B. Functional Testing:</b> Tập trung vào việc hệ thống LÀM GÌ (chức năng đúng/sai).<br>❌ <b>D. Regression Testing:</b> Kiểm tra sự ảnh hưởng của thay đổi code." },
    { q: "What is the primary purpose of Non-Functional Testing?", opts: ["To test how well software performs under specific conditions", "To ensure system meets specified requirements", "To verify correctness of individual units", "To validate integration of components"], ans: 0, exp: "<b>✅ Đáp án đúng là A: How well software performs</b><br>Functional Testing trả lời câu hỏi 'Hệ thống làm được cái gì?'. Non-Functional Testing trả lời câu hỏi 'Hệ thống làm điều đó TỐT ĐẾN MỨC NÀO?' (nhanh hay chậm, bảo mật hay không, dễ dùng hay khó).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Đây là mục đích chung của System Testing.<br>❌ <b>C:</b> Unit Testing.<br>❌ <b>D:</b> Integration Testing." },
    { q: "What is the purpose of Acceptance Testing?", opts: ["To verify correctness of individual units", "To ensure components function in isolation", "To test integration between modules", "To validate system meets business requirements"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Validate business requirements</b><br>Acceptance Testing (UAT) là chốt chặn cuối cùng. Mục tiêu là để khách hàng xác nhận phần mềm ĐÁP ỨNG NHU CẦU KINH DOANH và sẵn sàng để Go-live.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Unit Testing.<br>❌ <b>C:</b> Integration Testing." },
    { q: "What is the primary goal of System Testing?", opts: ["To test in production-like environment", "To verify each unit functions correctly", "To ensure system meets specified requirements", "To validate integration of components"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Ensure system meets specified requirements</b><br>System Testing kiểm tra TOÀN BỘ hệ thống (End-to-End) dựa trên tài liệu yêu cầu (SRS). Nó bao gồm cả Functional và Non-Functional.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Đây là điều kiện môi trường, không phải GOAL.<br>❌ <b>B:</b> Unit Testing.<br>❌ <b>D:</b> Integration Testing." },
    { q: "Which test level is often performed by end-users or clients?", opts: ["System Testing", "Unit Testing", "User Acceptance Testing", "Integration Testing"], ans: 2, exp: "<b>✅ Đáp án đúng là C: User Acceptance Testing (UAT)</b><br>UAT là giai đoạn duy nhất mà End-Users hoặc Client trực tiếp tham gia test để quyết định 'Accept' hay 'Reject' sản phẩm.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> Thường do đội ngũ Tester/QA chuyên nghiệp thực hiện.<br>❌ <b>B:</b> Do Developer thực hiện." },
    { q: "Which test level focuses on interaction between components or systems?", opts: ["Acceptance Testing", "System Testing", "Integration Testing", "Unit Testing"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Integration Testing</b><br>Integration Testing kiểm tra CÁC GIAO DIỆN (Interfaces) và sự trao đổi dữ liệu giữa các module. Nó tìm lỗi trong sự TƯƠNG TÁC chứ không phải lỗi nội tại của từng module.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Business requirements.<br>❌ <b>B:</b> Whole system behavior.<br>❌ <b>D:</b> Isolated component validation." },
    { q: "What is the purpose of the Unit Testing phase?", opts: ["To test individual components in isolation", "To ensure system performs under stress", "To validate system meets requirements", "To test entire system as a whole"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Individual components in isolation</b><br>Unit Testing cô lập một phần nhỏ nhất của code (hàm, class) để kiểm tra tính đúng đắn của logic nội tại, đảm bảo 'code chạy đúng như dev nghĩ'.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Stress Testing.<br>❌ <b>C:</b> System/Acceptance Testing.<br>❌ <b>D:</b> System Testing." },
    { q: "Which test level typically involves testing in simulated/actual production environment?", opts: ["Acceptance Testing", "System Testing", "Unit Testing", "Integration Testing"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Acceptance Testing</b><br>Để quyết định 'Accept', môi trường test phải GIỐNG NHẤT có thể với môi trường thật (Production) để tránh lỗi 'works on my machine'. System test cũng có thể dùng bản sao prod nhưng UAT bắt buộc tính chất này cao nhất.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, D:</b> Thường chạy trên môi trường QA/Staging với dữ liệu test.<br>❌ <b>C:</b> Chạy trên máy Dev (Local)." },
    { q: "Which test level focuses on successful deployment in target environment?", opts: ["Integration Testing", "Deployment Testing", "Unit Testing", "System Testing"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Deployment Testing</b><br>Deployment Testing (hay Installation Testing) kiểm tra quy trình cài đặt, cấu hình, và triển khai phần mềm lên môi trường đích có trơn tru không.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Tập trung vào tìm lỗi phần mềm, không phải lỗi quy trình deploy." },
    { q: "Regression testing is primarily associated with which test level?", opts: ["System Testing", "Unit Testing", "User Acceptance Testing", "Integration Testing"], ans: 0, exp: "<b>✅ Đáp án đúng là A: System Testing</b><br>Mặc dù Regression có thể làm ở mọi level, nhưng phổ biến nhất là mức System Testing - chạy lại bộ test suite chức năng để đảm bảo bản build mới không phá vỡ tính năng cũ.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Unit regression thường chạy tự động CI/CD.<br>❌ <b>C:</b> UAT thường ít khi chạy lại toàn bộ regression (tốn thời gian của khách).<br>❌ <b>D:</b> Có thể, nhưng System regression là thuật ngữ phổ biến nhất." }
];

// 4. Types of Testing (6 câu - Q1-6 section 2)
QUIZ_DATA.topics[3].questions = [
    { q: "Which of the following option is a Test Type?", opts: ["Acceptance testing", "System testing", "Component testing", "Functional testing"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Functional testing</b><br>Functional Testing là một LOẠI (Test Type) kiểm thử tập trung vào 'làm cái gì' (what the system does).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Acceptance, System, Component testing được ISTQB phân loại là CẤP ĐỘ (Test Levels) - trả lời cho câu hỏi 'kiểm thử ở giai đoạn nào/phạm vi nào'." },
    { q: "Which is a non-functional testing method? i) System testing ii) Performance testing iii) Availability testing", opts: ["i & iii", "i & ii", "ii & iii", "i"], ans: 2, exp: "<b>✅ Đáp án đúng là C: ii & iii</b><br>Performance (Hiệu năng) và Availability (Tính sẵn sàng) là các thuộc tính chất lượng PHI CHỨC NĂNG (Non-functional).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>i. System Testing:</b> Là Test Level, trong đó có thể thực hiện cả Functional và Non-functional testing, bản thân nó không phải là một method phi chức năng cụ thể." },
    { q: "Functional System Testing:", opts: ["Testing system's functions in relation to other systems", "Testing components containing system's functions", "Testing if system performs functions within time frame", "Testing overall end-to-end functionality"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Testing overall end-to-end functionality</b><br>Chức năng ở cấp độ hệ thống kiểm tra luồng nghiệp vụ từ đầu đến cuối (End-to-End) để đảm bảo hệ thống hoạt động như một khối thống nhất.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Đây là System Integration Testing.<br>❌ <b>B:</b> Unit/Component Testing.<br>❌ <b>C:</b> 'Time frame' liên quan đến Performance/Responese time." },
    { q: "Repetition of testing after changes to detect new errors is called:", opts: ["Negative Testing", "Confirmation Testing", "Regression Testing", "Re-testing"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Regression Testing</b><br>Regression Testing (Kiểm thử hồi quy) là việc chạy lại các test cases ĐÃ PASS trước đó để đảm bảo thay đổi code không vô tình gây ra lỗi mới (side effects).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Negative Testing:</b> Test trường hợp sai/lỗi.<br>❌ <b>B, D:</b> Confirmation Testing / Re-testing dùng để xác nhận bug đã sửa, không phải tìm lỗi mới do ảnh hưởng phụ." },
    { q: "The difference between Re-testing and Regression Testing is:", opts: ["Re-testing looks for side-effects; Regression ensures bugs are fixed", "Re-testing ensures bugs are fixed; Regression looks for side-effects", "Re-testing is after bugs fixed; Regression is earlier", "Re-testing by developers; Regression by testers"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Re-testing ensures bugs are fixed; Regression looks for side-effects</b><br>Đây là sự khác biệt cốt lõi:<br>- <b>Re-testing:</b> Kiểm tra lại đúng con bug đó xem đã fix chưa.<br>- <b>Regression:</b> Kiểm tra diện rộng xem có làm hỏng tính năng khác không.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Ngược lại hoàn toàn.<br>❌ <b>C:</b> Thường Re-test xong (bug closed) mới chạy Regression để chốt release.<br>❌ <b>D:</b> Cả hai thường do Tester làm." },
    { q: "Non-functional system testing includes:", opts: ["Testing system features using only necessary software", "Testing system's quality attributes, including performance and usability", "Testing to see where function is not working", "Testing system features for that function"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Testing system's quality attributes</b><br>Non-functional testing tập trung vào 'HOW' hệ thống hoạt động: Nhanh hay chậm? Dễ dùng không? Bảo mật không?<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Các mô tả này mơ hồ hoặc ám chỉ Functional testing (tính năng, hoạt động đúng sai)." }
];

// 5. Software Quality (10 câu - Q7-16 section 2)
QUIZ_DATA.topics[4].questions = [
    { q: "Đặc điểm nào KHÔNG phải là yếu tố quan trọng của Interaction Capability?", opts: ["Khả năng xử lý lỗi và thông báo cho người dùng", "Khả năng tùy biến giao diện người dùng", "Khả năng tương thích với các phần cứng khác nhau"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Khả năng tương thích với các phần cứng khác nhau</b><br>Đây thuộc về tính Tương thích (Compatibility) hoặc Portability, không phải là khả năng tương tác (Interaction) với người dùng.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Xử lý lỗi (Error handling) và Tùy biến (Customizability) đều ảnh hưởng trực tiếp đến trải nghiệm tương tác của người dùng." },
    { q: "Đặc tính nào trong ISO/IEC 25010 đề cập đến khả năng phần mềm hoạt động không lỗi?", opts: ["Tính tin cậy (Reliability)", "Tính khả dụng (Usability)", "Tính bảo trì (Maintainability)"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Tính tin cậy (Reliability)</b><br>Reliability đo lường mức độ hoạt động ổn định, không gặp sự cố (fail-free operation) trong một khoảng thời gian nhất định.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Usability:</b> Dễ sử dụng.<br>❌ <b>C. Maintainability:</b> Dễ bảo trì/sửa đổi." },
    { q: "Tính Safety có liên quan đến điều nào sau đây?", opts: ["Tốc độ xử lý khi gặp tình huống khẩn cấp", "Bảo mật hệ thống khỏi các cuộc tấn công", "Phát hiện và ngăn chặn lỗi có thể gây nguy hiểm"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Phát hiện và ngăn chặn lỗi có thể gây nguy hiểm</b><br>Trong context Software Quality, 'Safety' là khả năng hệ thống không gây hại cho người, tài sản hoặc môi trường (ví dụ: phần mềm y tế, hàng không).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Performance/Reliability.<br>❌ <b>B:</b> Security (Bảo mật thông tin)." },
    { q: "Đặc tính nào đánh giá mức độ phần mềm đáp ứng yêu cầu và mong đợi của người dùng?", opts: ["Tính năng (Functionality)", "Tính bảo mật (Security)", "Tính khả dụng (Usability)"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Tính năng (Functionality)</b><br>Functionality Suitability đánh giá xem phần mềm có cung cấp đúng và đủ các chức năng mà người dùng cần để hoàn thành mục tiêu hay không.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Security:</b> Chỉ về bảo vệ dữ liệu.<br>❌ <b>C. Usability:</b> Chỉ về trải nghiệm sử dụng." },
    { q: "Đặc tính nào liên quan đến mức độ dễ dàng người dùng có thể sử dụng phần mềm?", opts: ["Tính bảo mật (Security)", "Tính tin cậy (Reliability)", "Tính khả dụng (Usability)"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Tính khả dụng (Usability)</b><br>Usability (theo ISO 25010) bao gồm: Dễ học (Learnability), Dễ hiểu (Appropriateness Recognizability), và Dễ vận hành (Operability).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Không liên quan trực tiếp đến độ 'dễ dùng'." },
    { q: "Tính bảo trì (Maintainability) trong ISO/IEC 25010 đề cập đến điều gì?", opts: ["Khả năng thích nghi với yêu cầu thay đổi", "Khả năng phục hồi sau sự cố", "Khả năng được sửa chữa và cải tiến dễ dàng"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Khả năng được sửa chữa và cải tiến dễ dàng</b><br>Maintainability đo lường công sức cần thiết để Developer sửa lỗi, nâng cấp hoặc thích ứng code với môi trường mới. Code clean, modular cao thì Maintainability cao.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Portability/Adaptability.<br>❌ <b>B:</b> Recoverability (thuộc Reliability)." },
    { q: "Đặc tính nào liên quan đến khả năng hoạt động trên nhiều môi trường khác nhau?", opts: ["Tính tin cậy (Reliability)", "Tính tương thích (Compatibility)", "Tính hiệu suất (Performance)"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Tính tương thích (Compatibility)</b><br>Compatibility (hoặc Portability) đảm bảo phần mềm chạy tốt trên các OS, Browser, Device khác nhau mà không cần sửa đổi nhiều.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C:</b> Không đề cập đến sự đa dạng môi trường." },
    { q: "Tại sao Flexibility là một đặc tính quan trọng của phần mềm?", opts: ["Để tăng tốc độ thực thi", "Để giúp dễ dàng sửa lỗi", "Để giúp dễ dàng thích nghi với yêu cầu hoặc thay đổi mới"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Để giúp dễ dàng thích nghi với yêu cầu hoặc thay đổi mới</b><br>Flexibility (Tính linh hoạt) cho phép hệ thống mở rộng hoặc thay đổi cấu hình để đáp ứng business needs mới mà không cần đập đi xây lại.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Performance.<br>❌ <b>B:</b> Maintainability." },
    { q: "Đặc tính nào liên quan đến khả năng bảo vệ dữ liệu và thông tin khỏi mối đe dọa?", opts: ["Tính bảo mật (Security)", "Tính khả dụng (Usability)", "Tính hiệu suất (Performance)"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Tính bảo mật (Security)</b><br>Security đảm bảo 3 yếu tố CIA: Confidentiality (Bảo mật), Integrity (Toàn vẹn), Availability (Sẵn sàng) của dữ liệu.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C:</b> Không liên quan đến threats/attacks." },
    { q: "Tính hiệu suất (Performance) có thể đo bằng các yếu tố nào?", opts: ["Tốc độ xử lý, thời gian phản hồi, sử dụng tài nguyên", "Tính năng, khả năng sử dụng, tính bảo mật", "Độ tin cậy, khả năng bảo trì, tính tương thích"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Tốc độ xử lý, thời gian phản hồi, sử dụng tài nguyên</b><br>Performance Efficiency được đo lường cụ thể qua: Response Time (ms/s), Throughput (requests/s), và Resource Utilization (CPU/RAM %).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C:</b> Liệt kê tên các đặc tính chất lượng khác, không phải metrics đo lường Performance." }
];

// 6. Test Planning (9 câu - Q17-25 section 2)
QUIZ_DATA.topics[5].questions = [
    { q: "What is the primary focus of risk analysis in a test plan?", opts: ["Writing test scripts", "Identifying potential project risks that may impact testing", "Defining the test schedule", "Executing test cases"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Identifying potential project risks</b><br>Risk Analysis giúp xác định sớm các rủi ro (Product risks & Project risks) để có kế hoạch giảm thiểu (Mitigation plan), ví dụ: thiếu device test, requirement chưa rõ ràng.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Writing scripts:</b> Thuộc giai đoạn Implementation/Design.<br>❌ <b>C. Schedule:</b> Là một mục riêng trong Test Plan, thường dựa vào Risk để estimate.<br>❌ <b>D. Executing:</b> Thuộc giai đoạn Execution." },
    { q: "What is the purpose of a test strategy in relation to a test plan?", opts: ["It defines the overall testing approach", "It schedules testing activities", "It lists detailed test cases", "It identifies bugs"], ans: 0, exp: "<b>✅ Đáp án đúng là A: It defines the overall testing approach</b><br>Test Strategy trả lời câu hỏi 'Làm thế nào?' (How): Công cụ gì, môi trường nào, kỹ thuật gì (Analytical, Model-based...). Nó mang tính định hướng lâu dài.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Schedules:</b> Test Plan mới chứa lịch trình cụ thể (When/Who).<br>❌ <b>C. Detailed test cases:</b> Không nằm trong Strategy hay Plan.<br>❌ <b>D. Identifies bugs:</b> Kết quả của quá trình Test." },
    { q: "What is the difference between a test plan and a test case?", opts: ["Test plan outlines approach, test case details steps to execute", "Test cases and test plans serve the same purpose", "Both terms are interchangeable", "Test case outlines approach, test plan details steps"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Test plan outlines approach, test case details steps</b><br>Test Plan là Tài liệu quản lý (Management doc). Test Case là Tài liệu kỹ thuật (Technical doc) chứa các bước: Input -> Action -> Expected Result.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C:</b> Sai hoàn toàn về bản chất.<br>❌ <b>D:</b> Định nghĩa bị đảo ngược." },
    { q: "When should a test plan be created in the SDLC?", opts: ["After testing", "During requirements gathering", "During coding", "Before testing"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Before testing</b><br>Test Plan phải được phê duyệt TRƯỚC khi bắt đầu các hoạt động thiết kế và thực thi kiểm thử để định hướng cho cả team.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. After testing:</b> Vô nghĩa.<br>❌ <b>B. Requirements:</b> Quá sớm để có đủ thông tin chi tiết (dù có thể draft).<br>❌ <b>C. During coding:</b> Dev code thì Tester viết Plan, nhưng 'Before testing' là mốc thời gian chính xác nhất về logic quy trình." },
    { q: "Who is responsible for reviewing and approving the test plan?", opts: ["Project managers", "Developers", "Customers", "Testers"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Project Managers</b><br>Test Plan là tài liệu cam kết về phạm vi, thời gian, chất lượng nên cần Stakeholders quản lý (PM, Test Manager) phê duyệt.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Developers:</b> Không có quyền quyết định scope test.<br>❌ <b>C. Customers:</b> Thường chỉ quan tâm UAT Plan.<br>❌ <b>D. Testers:</b> Là người viết (Author), không phải người duyệt (Approver)." },
    { q: "What is the importance of defining entry and exit criteria in a test plan?", opts: ["To create test cases", "To identify bugs in code", "To estimate testing effort", "To determine when testing should start and end"], ans: 3, exp: "<b>✅ Đáp án đúng là D: To determine when testing should start and end</b><br>Entry Criteria: Đủ điều kiện để BẮT ĐẦU (VD: Code delivered, Environment ready). Exit Criteria: Đủ điều kiện để KẾT THÚC (VD: 100% Critical bugs fixed, Pass rate 95%).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Là các hoạt động khác, không phải mục đích của Criteria." },
    { q: "What is the significance of defining roles and responsibilities in a test plan?", opts: ["To identify who is responsible for what", "To assign blame in case of failure", "To write code", "To create additional test cases"], ans: 0, exp: "<b>✅ Đáp án đúng là A: To identify who is responsible for what</b><br>Phần Roles & Resp đảm bảo mọi thành viên (Test Lead, Tester, Automation Engineer) biết nhiệm vụ của mình để phối hợp nhịp nhàng.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Assign blame:</b> Tư duy sai lầm trong Agile/Modern working.<br>❌ <b>C, D:</b> Không liên quan." },
    { q: "What does 'test coverage' refer to in the context of a test plan?", opts: ["Time taken to execute test cases", "Scope of testing in terms of requirements covered", "Number of test cases executed", "Percentage of bugs found"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Scope of testing in terms of requirements covered</b><br>Test Coverage đo lường mức độ bao phủ của bộ test đối với Requirements (Requirement Coverage) hoặc đối với Code (Code Coverage).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Time:</b> Test Duration.<br>❌ <b>C. Number of cases:</b> Test count metric.<br>❌ <b>D. Bugs found:</b> Defect density." },
    { q: "What information is typically included regarding the test environment?", opts: ["Test schedule", "Hardware and software requirements", "Test case details", "Risk analysis"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Hardware and software requirements</b><br>Test Environment bao gồm: Server specs, Database config, OS version, Browser types, Network conditions... cần thiết để chạy test.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Là những mục riêng biệt trong Test Plan." }
];

// 7. Test Management (10 câu - Q1-10 section 3)
QUIZ_DATA.topics[6].questions = [
    { q: "What is the primary goal of Test Monitoring and Control in Test Management?", opts: ["To train new team members", "To develop the software", "To design test cases", "To ensure testing process runs as expected"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Ensure testing process runs as expected</b><br>Test Monitoring (Theo dõi) thu thập metric để so sánh Actual vs Plan. Test Control (Kiểm soát) đưa ra biện pháp chỉnh sửa khi có lệch hướng (ví dụ: thêm người để kịp deadline).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Training, coding, design là các activity cụ thể, không phải mục tiêu quản lý/giám sát." },
    { q: "What does Test Estimation primarily focus on?", opts: ["Approximately determining how long a task would take", "Deciding software's release date", "Assigning tasks to team members", "Determining project's total cost"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Approximately determining how long a task would take</b><br>Test Estimation dự đoán Cost (chi phí) và Effort (công sức/thời gian) để hoàn thành activities. Trả lời câu hỏi: 'Mất bao lâu để test xong?'.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Release date:</b> Do Stakeholders quyết định.<br>❌ <b>C. Assign tasks:</b> Là Resource Planning.<br>❌ <b>D. Total cost:</b> Project cost rộng hơn test cost." },
    { q: "Which kind of risk does not belong to Project Risk?", opts: ["Organization risk", "Product risk", "Technical risk", "Business risk"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Product risk - KHÔNG thuộc Project Risk</b><br>Rủi ro được chia thành 2 loại chính:<br>- <b>Product Risk (Quality Risk):</b> Liên quan đến bản thân phần mềm (Bug, Performance kém, Security hổng).<br>- <b>Project Risk:</b> Liên quan đến quản lý dự án (Thiếu người, Hết tiền, Trễ deadline).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Organization, Technical, Business status đều ảnh hưởng đến sự thành bại của DỰ ÁN, không phải lỗi của sản phẩm." },
    { q: "What is the role of a Test Administrator in the test management process?", opts: ["Analyzing software requirement specifications", "Reporting the defects", "Designing test scenarios", "Building up the test environment"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Building up the test environment</b><br>Test Administrator (hoặc Test Environment Manager) chịu trách nhiệm quản lý hạ tầng: Server, Network, Data, Tools để team Tester có môi trường làm việc.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Là nhiệm vụ của Test Analyst / Tester." },
    { q: "Which of the following is not a part of the Test Management process?", opts: ["Test Monitoring and Control", "Test Planning", "Code Development", "Risk Analysis"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Code Development</b><br>Test Management quản lý quy trình kiểm thử. Code Development là quy trình phát triển (Dev).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Đều là các hoạt động cốt lõi của Test Management theo chuẩn ISTQB." },
    { q: "Which technique is not used for Test Estimation?", opts: ["Work Breakdown Structure", "Wideband Delphi technique", "Function Point Analysis", "Agile Methodology"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Agile Methodology</b><br>Agile là một PHƯƠNG PHÁP phát triển phần mềm (Development Methodology), không phải là một kỹ thuật ước lượng (Estimation Technique).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. WBS:</b> Chia nhỏ task để estimate.<br>❌ <b>B. Wideband Delphi:</b> Kỹ thuật đồng thuận nhóm (Planning Poker).<br>❌ <b>C. Function Point:</b> Estimate dựa trên tính năng." },
    { q: "In Function Point Method, what weightage is assigned to a 'Complex' task?", opts: ["5", "10", "3", "1"], ans: 0, exp: "<b>✅ Đáp án đúng là A: 5</b><br>Theo chuẩn Function Point Analysis (FPA), trọng số độ phức tạp thường là:<br>- Simple (Đơn giản): 1<br>- Average (Trung bình): 3<br>- Complex (Phức tạp): 5<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>C. 3:</b> Average.<br>❌ <b>D. 1:</b> Simple." },
    { q: "What is the primary objective of Test Management?", opts: ["Designing complex test cases", "Focusing only on automated testing", "Reducing cost of development", "Ensuring high quality and effectiveness of testing"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Ensures high quality and effectiveness of testing</b><br>Mục tiêu tối thượng: Đảm bảo quy trình test HIỆU QUẢ (tìm được bug quan trọng) và CHẤT LƯỢNG (đúng tiến độ, đúng scope) để giảm rủi ro release.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Chỉ là phương tiện/kỹ thuật.<br>❌ <b>C:</b> Reduce cost là hệ quả, không phải mục tiêu trực tiếp." },
    { q: "What is the first step in test estimation using Work Breakdown Structure?", opts: ["Dividing the whole project task into subtasks", "Assigning tasks to team members", "Calculating total project duration", "Estimating cost for each task"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Dividing the whole project task into subtasks</b><br>WBS (Work Breakdown Structure) bắt đầu bằng việc 'rã' dự án lớn thành các module nhỏ, rồi tasks nhỏ hơn cho đến khi có thể estimate được.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Các bước này chỉ thực hiện được SAU KHI đã có danh sách subtasks từ bước A." },
    { q: "Which aspect of Test Management involves defining scope, approach, resources, and schedule?", opts: ["Test Planning", "Test Implementation", "Test Design", "Test Execution"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Test Planning</b><br>Planning trả lời 4 câu hỏi chính: Test cái gì (Scope)? Test như thế nào (Approach)? Cần ai/cái gì (Resources)? Khi nào xong (Schedule)?<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Là các giai đoạn thực thi chi tiết sau khi đã có Plan." }
];

// 8. Test Cases (10 câu - Q11-20 section 3)
QUIZ_DATA.topics[7].questions = [
    { q: "A test case is developed based on …", opts: ["Test progress report", "Bug report", "Test suite", "Test condition"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Test condition</b><br>Test Condition là điều kiện cần kiểm tra (được trích xuất từ Requirements). Test Case là các bước cụ thể để kiểm tra Condition đó.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Là output sau khi test.<br>❌ <b>C:</b> Test Suite là tập hợp chứa Test Cases." },
    { q: "It is a condition that must be met before executing a test case.", opts: ["Expected result", "Precondition", "Test case title", "Test steps"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Precondition</b><br>Precondition (Điều kiện tiên quyết) là trạng thái hệ thống cần có TRƯỚC KHI chạy test steps (VD: User phải logged in, Database phải có data).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Expected result:</b> Kết quả mong đợi SAU KHI chạy.<br>❌ <b>D. Test steps:</b> Hành động TRONG KHI chạy." },
    { q: "Which field should be filled in the test execution phase?", opts: ["Steps to reproduce", "Actual result", "Title", "Expected result"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Actual result</b><br>Trong lúc chạy test (Execution), Tester quan sát hệ thống và ghi lại Kết quả thực tế (Actual Result). Các trường khác đã được điền từ lúc Design.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Steps to reproduce:</b> Dùng trong Bug Report.<br>❌ <b>C, D:</b> Define trong Test Case Design." },
    { q: "Test cases should be written for which level of testing?", opts: ["System testing, Acceptance testing", "Only System Testing", "Any test level can have written test cases", "Unit testing, Integration testing"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Any test level can have written test cases</b><br>Test Case là tài liệu mô tả cách test, cần thiết cho mọi level từ Unit (Unit test cases), Integration, System đến UAT.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Đều thiếu sót các level khác." },
    { q: "Blocked/Skipped test case means …", opts: ["Test case executed and actual result is different from expected", "The test case can't be executed", "Test case executed and actual result equals expected", "The test case is not executed"], ans: 1, exp: "<b>✅ Đáp án đúng là B: The test case can't be executed</b><br>- <b>Blocked:</b> Không chạy được do lỗi môi trường, lỗi data, hoặc lỗi chức năng chặn đường (Blocker).<br>- <b>Skipped:</b> Cố tình bỏ qua (không chạy) trong cycle này.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Failed.<br>❌ <b>C:</b> Passed." },
    { q: "The following steps are the best way to test steps (sequential UI steps example).", opts: ["False", "True"], ans: 0, exp: "<b>✅ Đáp án đúng là A: False</b><br>Viết test steps quá chi tiết kiểu 'Click A -> Wait -> Click B' (Sequential UI steps) thường KHÔNG tốt vì khó bảo trì khi UI thay đổi. Nên viết theo hướng 'Logical Action' hoặc 'High-level flows'.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. True:</b> Sequential steps dễ vỡ (fragile) và tốn cost bảo trì." },
    { q: "What does a blocked/skipped test case mean?", opts: ["We were not able to execute because it depends on another test case", "We executed and actual result is different than expected", "We executed and actual result is the same as expected"], ans: 0, exp: "<b>✅ Đáp án đúng là A: We were not able to execute because it depends on another test case</b><br>Một nguyên nhân phổ biến của Blocked test là Dependency: Test case A tạo data, A fail -> B bị Blocked (không có data để chạy).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Failed.<br>❌ <b>C:</b> Passed." },
    { q: "Testing E-wallet app by transferring more than balance is considered as a …", opts: ["Positive test case", "Negative test case"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Negative test case</b><br>Negative Testing (Test tiêu cực) kiểm tra cách hệ thống xử lý lỗi khi Input KHÔNG HỢP LỆ (Số tiền > Số dư).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Positive test case:</b> Test luồng đi đúng (Happy Path), ví dụ: Chuyển tiền trong giới hạn số dư." },
    { q: "We should never fill the actual result field until executing the test case.", opts: ["True", "False"], ans: 0, exp: "<b>✅ Đáp án đúng là A: True</b><br>Trước khi chạy, Actual Result là ẩn số. Nếu điền trước, đó là 'Fake results' và vi phạm đạo đức nghề nghiệp/quy trình kiểm thử.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Sai vì điền trước là đoán mò." },
    { q: "iPhone 8 - iOS 15.1 - 5G Network. Which are correct environment dimensions?", opts: ["Software - hardware - network", "Network - software - hardware", "Hardware - software - network", "Hardware - network - software"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Hardware - Software - Network</b><br>Phân loại đúng:<br>- iPhone 8 = <b>Hardware</b> (Thiết bị)<br>- iOS 15.1 = <b>Software</b> (Hệ điều hành)<br>- 5G = <b>Network</b> (Mạng)<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Sai thứ tự tương ứng." }
];

// 9. Bug Report (5 câu - Q21-25 section 3)
QUIZ_DATA.topics[8].questions = [
    { q: "In bug reporting, what does the 'Status' field indicate?", opts: ["Location where bug was found", "Timeline for next software update", "Severity level of the bug", "Current state of bug (e.g., New, Closed, Reopened)"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Current state of bug (e.g., New, Closed, Reopened)</b><br>Status (Trạng thái) cho biết con bug đang nằm ở đâu trong Bug Lifecycle: Mới tạo (New) -> Dev đang sửa (In Progress) -> Đã sửa (Fixed) -> Đóng (Closed).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Location, Timeline, Severity là các trường thông tin khác." },
    { q: "What does Severity in a bug report indicate?", opts: ["Complexity of the bug", "Impact of the defect on the application", "Urgency with which bug should be fixed", "Number of users affected"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Impact of the defect on the application</b><br>Severity (Mức độ nghiêm trọng) đo lường ẢNH HƯỞNG KỸ THUẬT: Crash app (Critical), Sai chức năng chính (Major), Sai giao diện (Minor).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>C. Urgency:</b> Là Priority (Độ ưu tiên) - đo lường TỐC ĐỘ cần fix (kinh doanh)." },
    { q: "What does 'Status = Re-Open' imply in a Bug Life Cycle?", opts: ["Bug previously marked as resolved has reappeared or was not fixed", "Bug has been fixed and is pending review", "Bug report needs more information", "Bug is low priority"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Bug previously marked as resolved has reappeared</b><br>Re-Open xảy ra khi: Dev báo 'Fixed' -> Tester kiểm tra lại thấy VẪN LỖI -> Đẩy lại trạng thái Re-Open.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Fixed / Resolved.<br>❌ <b>C:</b> Need info / Incomplete." },
    { q: "Which of the following is NOT an essential element of a bug report?", opts: ["Bug ID", "Name of the customer", "Problem summary", "Function name where bug was found"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Name of the customer</b><br>Bug Report là tài liệu kỹ thuật nội bộ giữa Tester và Dev. Tên khách hàng (Customer Name) thường nằm trong CRM/Support ticket, không bắt buộc trong Bug Report của engineering.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Bug ID (để track), Summary (để hiểu nhanh), Function (để tìm chỗ sửa) là BẮT BUỘC." },
    { q: "Which is a factor in determining bug report priority?", opts: ["Impact of bug on core functionalities", "Software release date", "Geographical location of reporter", "Color scheme of software"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Impact of bug on core functionalities</b><br>Priority thường tỷ lệ thuận với Severity. Nếu bug ảnh hưởng feature chính (Impact cao) -> Cần fix gấp (Priority cao).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Release date là yếu tố phụ (thúc đẩy priority). Location/Color không liên quan." }
];

// 10. Test Approaches (5 câu - Q26-30 section 3)
QUIZ_DATA.topics[9].questions = [
    { q: "What is the definition of 'test technique'?", opts: ["Sequence of instructions for test execution", "Set of test scripts", "Procedure used to define test conditions, design test cases, and specify test data", "Documentation of test activities"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Procedure to define conditions, design cases, specify data</b><br>Test Technique là quy trình hệ thống hóa để biến Test Basis (tài liệu) thành Test Cases. Nó giúp trả lời câu hỏi: 'Làm sao để test hiệu quả nhất?'.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Test Procedure.<br>❌ <b>B:</b> Test Suite.<br>❌ <b>D:</b> Test Ware/Documentation." },
    { q: "The testing approach which tests as a user with access to internals is:", opts: ["Grey-box testing", "White-box testing", "Black-box testing", "Not applicable"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Grey-box testing</b><br>Grey-box Testing kết hợp Black-box (test như user) và White-box (biết cấu trúc DB, code, algo). Ví dụ: Test login và check cả database xem trạng thái user.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. White-box:</b> Thuần túy kỹ thuật, không đóng vai user.<br>❌ <b>C. Black-box:</b> Hoàn toàn mù (blind) về bên trong." },
    { q: "The testing approaches are classified into:", opts: ["Three major categories: black-box, white-box, and experience-based", "Two major categories", "Four major categories", "Three categories: boundary value, decision table, state transition"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Three major categories: Black-box, White-box, and Experience-based</b><br>Theo chuẩn ISTQB, 3 nhóm kỹ thuật kiểm thử chính là:<br>1. <b>Black-box:</b> Dựa trên đặc tả (Specification-based).<br>2. <b>White-box:</b> Dựa trên cấu trúc (Structure-based).<br>3. <b>Experience-based:</b> Dựa trên kinh nghiệm (Error guessing, Exploratory).<br><i>(Lưu ý: Grey-box thường được nhắc đến trong thực tế nhưng Experience-based mới là category chính thống trong syllabus).</i><br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>D:</b> Boundary, Decision table... là tên CÁC KỸ THUẬT con của Black-box." },
    { q: "'Detailed design and internal structure' are examples of test basis for …", opts: ["Experience-based test technique", "None of the above", "Black-box test technique", "White-box test technique"], ans: 3, exp: "<b>✅ Đáp án đúng là D: White-box test technique</b><br>White-box cần 'Test Basis' là các tài liệu kỹ thuật chi tiết: Code structure, Database design, System architecture.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>C. Black-box:</b> Dựa trên Requirements, User Stories, Use Cases (External behavior).<br>❌ <b>A. Experience-based:</b> Dựa trên kiến thức, trực giác (Exploratory, Error guessing)." },
    { q: "'Use cases' are examples of test basis for …", opts: ["Experience-based test technique", "None of the above", "Black-box test technique", "White-box test technique"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Black-box test technique</b><br>Use Cases mô tả hành vi hệ thống từ góc nhìn người dùng (User view), do đó là cơ sở để thiết kế Black-box tests.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>D. White-box:</b> Cần code logic, không phải user scenarios.<br>❌ <b>A. Experience:</b> Không phụ thuộc document." }
];

// 11. Domain Testing (8 câu - Q1-8 section 4)
QUIZ_DATA.topics[10].questions = [
    { q: "In 'Equivalence partitioning', the partitions are called …", opts: ["Equivalence classes", "Sub partitions", "Valid equivalence partitions", "Invalid equivalence partitions"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Equivalence classes</b><br>Trong kỹ thuật Phân vùng tương đương (EP), các tập hợp dữ liệu được gọi là 'Equivalence Classes' (Lớp tương đương).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>C, D:</b> Valid/Invalid là 2 loại cụ thể của Equivalence classes, không phải tên gọi chung." },
    { q: "In 'Equivalence partitioning', partitions that contain valid values are called …", opts: ["Invalid equivalence partitions", "Valid equivalence partitions", "Equivalence classes", "Sub partitions"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Valid equivalence partitions</b><br>Valid Partitions chứa các giá trị mà hệ thống CHẤP NHẬN và xử lý bình thường.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Invalid:</b> Chứa giá trị hệ thống từ chối/báo lỗi.<br>❌ <b>C. Equivalence classes:</b> Tên chung." },
    { q: "If we have values 0, 3, 6, 9 for equivalence partitions. Which rule is applicable on '9'?", opts: ["Each value must belong to one and only one equivalence partition", "Each value can belong to one or more equivalence partitions", "Any partition may be divided into sub-partitions if required", "Not applicable"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Each value must belong to one and only one partition</b><br>Nguyên tắc 'Mutual Exclusivity': Các phân vùng không được chồng chéo nhau. Số 9 chỉ được thuộc về 1 phân vùng duy nhất.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B:</b> Nếu thuộc 2 phân vùng thì test case sẽ bị nhập nhằng (ambiguous)." },
    { q: "The coverage of Boundary Value Analysis is measured as …", opts: ["None of above", "Number of boundary values tested / total identified boundary test values", "Number of tested equivalence partitions / total boundary test values", "Number of boundary values tested / total identified equivalence partitions"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Number of boundary values tested / total identified boundary values</b><br>Công thức Coverage BVA = (Số điểm biên đã test / Tổng số điểm biên xác định được) * 100%.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>C, D:</b> Công thức sai, lẫn lộn giữa EP và BVA." },
    { q: "Boundary value analysis is considered as an extension of …", opts: ["Use cases testing", "Equivalence partitioning", "State transition testing", "Decision table testing"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Equivalence partitioning</b><br>BVA luôn đi kèm với EP. Sau khi chia Partition (EP), ta lấy các giá trị ở mép (Boundary) để test kỹ hơn -> BVA là extension của EP.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Không có quan hệ trực tiếp 'extension' với BVA." },
    { q: "The equivalence partitioning coverage is measured as …", opts: ["Number tested by at least ONE value / total identified", "Number tested by at least THREE values / total", "Number tested by at least TWO values / total", "Number tested by at least FOUR values / total"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Number tested by at least ONE value / total identified</b><br>Theo lý thuyết EP: Test 1 giá trị đại diện là đủ cho cả vùng. Coverage = (Số partition đã test ít nhất 1 giá trị / Tổng số partitions) * 100%.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Không cần test nhiều giá trị cho 1 partition (trừ khi kết hợp BVA)." },
    { q: "In 'Equivalence partitioning', partitions that contain invalid values are called …", opts: ["Invalid equivalence partitions", "Sub partitions", "Valid equivalence partitions", "Equivalence classes"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Invalid equivalence partitions</b><br>Invalid Partitions chứa các giá trị mà hệ thống cần TỪ CHỐI hoặc BÁO LỖI.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. Sub partitions:</b> Chia nhỏ partition.<br>❌ <b>C. Valid:</b> Giá trị hợp lệ." },
    { q: "Boundary value analysis can be applied on which test levels?", opts: ["Unit and integration testing", "Unit, integration and system testing", "Unit testing only", "Unit, integration, system and acceptance testing"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Unit, integration, system and acceptance testing</b><br>BVA áp dụng được ở MỌI test level, miễn là có input data có thể sắp xếp thứ tự (ordered data).<br>- Unit: Check logic if (x > 10)<br>- System: Check input field limit<br>- Acceptance: Check business rules limits" }
];

// 12. Decision Table Testing (6 câu - Q9-14 section 4)
QUIZ_DATA.topics[11].questions = [
    { q: "The common minimum coverage standard for decision table testing is …", opts: ["At least one test case per decision rule", "At least three test cases per decision rule", "At least four test cases per decision rule", "At least two test cases per decision rule"], ans: 0, exp: "<b>✅ Đáp án đúng là A: At least one test case per decision rule</b><br>Tiêu chuẩn tối thiểu: Mỗi cột (Rule) trong bảng quyết định phải được cover bởi ít nhất 1 test case.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Thừa thãi. Logic giống nhau thì 1 test case là đủ để verify rule đó." },
    { q: "The values in decision table testing are usually shown as … and may have …", opts: ["Discrete value only / same types", "Boolean or discrete values / same types", "Boolean or discrete values / different types", "Discrete values only / different types"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Boolean or discrete values / different types</b><br>Conditions thường là:<br>- Boolean: True/False<br>- Discrete: Red/Green/Blue<br>Các conditions có thể khác nhau về kiểu dữ liệu.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> Thiếu Boolean (rất phổ biến).<br>❌ <b>B:</b> Conditions không bắt buộc cùng type." },
    { q: "For conditions with yes/no questions, the number of table rules equals … (n = number of conditions)", opts: ["2n", "n²", "2ⁿ", "n+2"], ans: 2, exp: "<b>✅ Đáp án đúng là C: 2ⁿ</b><br>Công thức tính số rules tối đa: 2 mũ n (với n là số điều kiện Yes/No).<br>Ví dụ: 3 điều kiện (Age>18, HasMoney, IsMember) -> 2³ = 8 rules.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. 2n:</b> Sai toán học.<br>❌ <b>B. n²:</b> Sai toán học." },
    { q: "In decision table testing, each column corresponds to a …", opts: ["Decision rule", "Decision partition", "Not applicable", "Decision coverage"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Decision rule</b><br>Mỗi cột đại diện cho một RULE: \"Nếu Condition A=True VÀ Condition B=False THÌ Action = X\".<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, D:</b> Không phải thuật ngữ chuẩn của Decision Table." },
    { q: "Coverage in decision table testing is measured as …", opts: ["Number of decision rules tested by at least two test cases / total", "Number of decision rules tested by at least one test case / total", "Number tested by at least three test cases / total", "Not applicable"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Number of decision rules tested by at least one test case / total</b><br>Công thức Coverage = (Số Rules đã test / Tổng số Rules) * 100%.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C:</b> Yêu cầu test >1 lần cho 1 rule là không cần thiết cho minimum coverage." },
    { q: "When different combinations of conditions result in different outcomes, which technique is used?", opts: ["Decision coverage", "Boundary value analysis", "Decision table", "Equivalence partitioning"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Decision table</b><br>Đây là keyword nhận biết Decision Table: Kiểm tra sự phức tạp của việc KẾT HỢP NHIỀU CONDITIONS (Combinations).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. BVA:</b> Focus vào biên đơn lẻ.<br>❌ <b>D. EP:</b> Focus vào dải giá trị đơn lẻ." }
];

// 13. State Transition Testing (9 câu - Q15-23 section 4)
QUIZ_DATA.topics[12].questions = [
    { q: "Every independent transition requires a separate test case.", opts: ["True", "False"], ans: 0, exp: "<b>✅ Đáp án đúng là A: True</b><br>Mỗi mũi tên chuyển đổi (Transition) độc lập nên được cover bởi 1 test case để đảm bảo nó hoạt động đúng.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B. False:</b> Nếu gộp chung có thể khó debug khi fail." },
    { q: "It is the state in which you cannot move from it to another state.", opts: ["Start state", "Transition state", "Alive state", "Dead state"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Dead state</b><br>Dead State (hay Final State) là điểm kết thúc, từ đó không thể chuyển sang trạng thái nào khác (Ví dụ: Trạng thái 'Deleted' hoặc 'Cancelled' trong một số flow).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. Start state:</b> Điểm bắt đầu.<br>❌ <b>C. Alive state:</b> Vẫn còn active." },
    { q: "State transition coverage is measured as …", opts: ["Number of valid events / total states or transitions", "Number of invalid events / total states or transitions", "Number of states or transitions tested / total states or transitions", "Not applicable"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Number of states or transitions tested / total</b><br>Coverage = (Số States hoặc Transitions đã test / Tổng số States hoặc Transitions Identified) * 100%.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Valid/Invalid events là input, coverage tính trên State/Transition." },
    { q: "Based on State Transition Diagram of a switch, which test case is invalid?", opts: ["ON to FAULT", "OFF to ON", "FAULT to ON", "ON to OFF"], ans: 2, exp: "<b>✅ Đáp án đúng là C: FAULT to ON</b><br>Logic thông thường: Khi thiết bị bị LỖI (FAULT), nó thường phải được Tắt (OFF) hoặc Reset trước khi Bật lại (ON). Chuyển trực tiếp FAULT -> ON thường là invalid transition.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Các chuyển đổi bình thường của công tắc." },
    { q: "A 'State transition table' shows …", opts: ["Valid and invalid transitions", "Not applicable", "Invalid transitions only", "Valid transitions only"], ans: 0, exp: "<b>✅ Đáp án đúng là A: Valid and invalid transitions</b><br>Bảng chuyển đổi trạng thái (Table) liệt kê đầy đủ ma trận State x Event, nên thể hiện được CẢ: <br>- Valid Transitions (Có hành động)<br>- Invalid Transitions (Không hành động hoặc Báo lỗi)<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>D. Valid transitions only:</b> State Diagram thường chỉ vẽ valid transitions cho đỡ rối, nhưng Table thì full." },
    { q: "Which statement is correct about 'State transition diagrams'?", opts: ["Shows both possible and impossible states", "Not applicable", "Shows only the possible software states", "Shows only the impossible software states"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Shows only the possible software states</b><br>Diagram chỉ hiển thị những gì CÓ THỂ xảy ra (Possible States & Transitions). Những transition vô lý thường được ẩn đi.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> Impossible states không vẽ lên diagram làm gì." },
    { q: "Given the battery charger state model, which sequence has highest transition coverage?", opts: ["OFF→WAIT→OFF→WAIT→TRICKLE→CHARGE→HIGH→CHARGE→LOW", "HIGH→CHARGE→LOW→CHARGE→TRICKLE→WAIT→TRICKLE→WAIT→TRICKLE", "WAIT→TRICKLE→WAIT→OFF→WAIT→TRICKLE→CHARGE→LOW→CHARGE", "WAIT→TRICKLE→CHARGE→HIGH→CHARGE→TRICKLE→WAIT→OFF→WAIT"], ans: 3, exp: "<b>✅ Đáp án đúng là D: WAIT→TRICKLE→CHARGE→HIGH→CHARGE→TRICKLE→WAIT→OFF→WAIT</b><br>Chuỗi này đi qua nhiều cặp trạng thái khác nhau nhất coverage cao nhất. (Phân tích chi tiết: đi qua hầu hết các state: Wait, Trickle, Charge, High, Off).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, C:</b> Lặp lại nhiều bước giống nhau (Redundant), không cover rộng bằng D." },
    { q: "Which is true in the context of State Transition Testing?", opts: ["It is a black-box technique", "It covers all possible conditions", "It is used to test system behavior under varying inputs", "All the previous"], ans: 3, exp: "<b>✅ Đáp án đúng là D: All the previous</b><br>1️⃣ Là Black-box technique (ISTQB).<br>2️⃣ Cover các state conditions.<br>3️⃣ Test behavior thay đổi theo input và history (state).<br>=> Tất cả đều đúng." },
    { q: "Given the state transition, which series provides 100% 0-switch coverage?", opts: ["ABECFD", "ABEBCD", "ABECFF", "ABCFD"], ans: 0, exp: "<b>✅ Đáp án đúng là A: ABECFD</b><br>0-switch coverage = Đi qua tất cả các cạnh (transitions) ít nhất 1 lần.<br>Chuỗi ABECFD duyệt qua các đường đi cần thiết để cover toàn bộ graph (dựa trên giả định mô hình standard).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Bỏ sót một số transitions." }
];

// 14. Use Case Testing (5 câu - Q1-5 section 5)
QUIZ_DATA.topics[13].questions = [
    { q: "Which statements are true about use case testing? (1) Use case can be described as interactions, activities, and preconditions. (2) Use cases can include variations such as error handling. (3) Code is designed to exercise defined behaviors.", opts: ["1, 2 are true / 3 is false", "1 is true / 2, 3 are false", "1, 2, 3 are false", "1, 2, 3 are true"], ans: 0, exp: "<b>✅ Đáp án đúng là A: 1, 2 true / 3 false</b><br>(1) Đúng: Use case gồm interactions, preconditions... (2) Đúng: Gồm cả exception flow (error handling). (3) Sai: Use case testing KIỂM TRA behavior, không phải 'design code' (câu này tối nghĩa, nhưng code design thuộc white-box/implementation).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Sai đánh giá các ý trên." },
    { q: "Use cases specify behaviors that a subject can perform with …", opts: ["Not applicable", "Only two actors", "Only one actor", "One or more actors"], ans: 3, exp: "<b>✅ Đáp án đúng là D: One or more actors</b><br>Use Case mô tả tương tác giữa hệ thống và 'Actors'. Có thể có 1 actor (User) hoặc nhiều actors (User, Admin, External System, Timer...).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C:</b> Không giới hạn số lượng." },
    { q: "Which of the following is commonly used technique in use-case testing?", opts: ["White-box testing", "Stress testing", "Scenario-based testing", "Boundary value analysis"], ans: 2, exp: "<b>✅ Đáp án đúng là C: Scenario-based testing</b><br>Use Case thường được test bằng cách viết 'Scenarios' (Kịch bản kiểm thử): Happy path scenario, Alternative path scenario, Error path scenario.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. White-box:</b> Kỹ thuật khác.<br>❌ <b>B. Stress:</b> Performance.<br>❌ <b>D. BVA:</b> Kỹ thuật Black-box khác." },
    { q: "What is use-case testing?", opts: ["Testing performance under heavy load", "Testing security features", "Testing individual components", "Testing system functionality based on real-world scenarios"], ans: 3, exp: "<b>✅ Đáp án đúng là D: Testing functionality based on real-world scenarios</b><br>Use Case phản ánh cách người dùng THỰC SỰ dùng hệ thống -> Giúp tìm defects trong quy trình nghiệp vụ thực tế.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Đó là Performance/Security testing.<br>❌ <b>C:</b> Unit/Component testing." },
    { q: "What is a key special attribute of use-case testing?", opts: ["Only applicable during development", "Emphasizes interaction between system and users", "Focuses solely on unit testing", "Concerned mainly with system architecture"], ans: 1, exp: "<b>✅ Đáp án đúng là B: Emphasizes interaction between system and users</b><br>Giá trị cốt lõi của Use Case là tập trung vào TƯƠNG TÁC (Interactions) và GIAO DIỆN NGƯỜI DÙNG (dưới dạng các bước hành động).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Áp dụng cả UAT.<br>❌ <b>D:</b> Không quan tâm architecture bên trong." }
];

// 15. GUI Testing (10 câu - Q6-15 section 5)
QUIZ_DATA.topics[14].questions = [
    { q: "Which of the following is a common GUI bug?", opts: ["Database overload", "Hardware compatibility", "Incorrect field default", "Slow processing speed"], ans: 2, exp: "✅ C. Incorrect field default: Đúng - Đây là lỗi GUI phổ biến: field hiển thị giá trị default SAI. ❌ A. Database: Backend issue. ❌ B. Hardware: Không phải GUI bug. ❌ D. Slow speed: Performance issue." },
    { q: "What is a common GUI bug related to data handling?", opts: ["Mishandling of server process failures", "Inadequate data encryption", "Inefficient data storage", "Overuse of data analytics"], ans: 0, exp: "✅ A. Mishandling server process failures: Đúng - GUI không xử lý đúng khi server lỗi (hiển thị error không rõ ràng). ❌ B, C, D đều là backend/infrastructure issues, không phải GUI bugs." },
    { q: "What is a common challenge in GUI testing?", opts: ["Limited programming languages", "Rapid UI changes", "High cost of software", "Lack of user feedback"], ans: 1, exp: "✅ B. Rapid UI changes: Đúng - GUI thay đổi LIÊN TỤC là thách thức lớn nhất, phải update test scripts thường xuyên. ❌ A, C, D không phải challenges đặc thù của GUI testing." },
    { q: "What is an example solution to integrating GUI testing with backend systems?", opts: ["Focusing only on frontend testing", "Using more powerful computers", "Implementing end-to-end testing strategies", "Reducing backend complexity"], ans: 2, exp: "✅ C. End-to-end testing strategies: Đúng - E2E testing tích hợp GUI với backend để test toàn bộ flow. ❌ A: Thiếu backend integration. ❌ B, D: Không giải quyết vấn đề integration." },
    { q: "What is a solution to ensure complete test coverage in GUI testing?", opts: ["Reducing the scope of testing", "Developing a comprehensive test strategy", "Limiting testing to critical functions only", "Increasing the number of testers"], ans: 1, exp: "✅ B. Comprehensive test strategy: Đúng - Cần CHIẾN LƯỢC TEST TOÀN DIỆN để đảm bảo coverage đầy đủ. ❌ A, C: Giảm scope = giảm coverage. ❌ D: Số lượng không đảm bảo comprehensive coverage." },
    { q: "In GUI testing, what is a challenge with test data and environment setup?", opts: ["Limited access to testing tools", "Inconsistent team skill levels", "High license costs", "Difficulty in creating and managing test data"], ans: 3, exp: "✅ D. Difficulty in creating/managing test data: Đúng - Tạo và quản lý TEST DATA cho GUI testing rất phức tạp (nhiều scenarios, states). ❌ A, B, C không phải challenges đặc thù của test data/environment." },
    { q: "Which is considered a common UI bug in GUI testing?", opts: ["Database connectivity problems", "Alignment and layout issues in the interface", "Backend performance issues", "Server-side errors"], ans: 1, exp: "✅ B. Alignment and layout issues: Đúng - Lỗi về ALIGNMENT và LAYOUT là UI bugs phổ biến nhất. ❌ A, C, D đều là backend/infrastructure issues, không phải UI bugs." },
    { q: "What approach is suggested for testing GUIs for different languages and cultures?", opts: ["Reducing supported languages", "Utilizing localization testing tools", "Outsourcing testing", "Focusing only on primary markets"], ans: 1, exp: "✅ B. Localization testing tools: Đúng - Dùng công cụ LOCALIZATION TESTING để test GUI với các ngôn ngữ/văn hóa khác nhau. ❌ A, D: Giảm nhu cầu, không giải quyết. ❌ C: Không đảm bảo chất lượng." },
    { q: "Which tool is commonly used for GUI testing?", opts: ["Version control systems", "IDEs", "Automated GUI testing tools", "Project management software"], ans: 2, exp: "✅ C. Automated GUI testing tools: Đúng - Các tools như Selenium, Appium, TestComplete được dùng để AUTOMATE GUI testing. ❌ A. VCS: Quản lý code. ❌ B. IDEs: Viết code. ❌ D. PM software: Quản lý project." },
    { q: "What is a recommended solution for managing frequent UI changes in GUI testing?", opts: ["Using less complex UI", "Increasing team size", "Implementing a robust test automation framework", "Reducing testing frequency"], ans: 2, exp: "✅ C. Robust test automation framework: Đúng - Framework AUTOMATION mạnh mẽ giúp dễ dàng update khi UI thay đổi (Page Object Model, etc.). ❌ A, D: Không thực tế. ❌ B: Số lượng không giải quyết maintenance." }
];

// 16. Security Testing (10 câu - Q16-25 section 5)
QUIZ_DATA.topics[15].questions = [
    { q: "What is the main purpose of Penetration Testing?", opts: ["To simulate a real-world attack", "To validate UI", "To verify data integrity", "To assess performance"], ans: 0, exp: "✅ A. Simulate real-world attack: Đúng - Pentest MÔ PHỎNG tấn công thực tế để tìm lỗ hổng bảo mật. ❌ B. Validate UI: đó là GUI testing. ❌ C. Data integrity: đó là Database testing. ❌ D. Performance: đó là Performance testing." },
    { q: "Which security testing technique involves analyzing source code for vulnerabilities?", opts: ["Black-box testing", "Gray-box testing", "Penetration testing", "White-box testing"], ans: 3, exp: "✅ D. White-box testing: Đúng - PHÂN TÍCH SOURCE CODE để tìm vulnerabilities = White-box/Static Analysis. ❌ A. Black-box: Không biết code. ❌ B. Gray-box: Biết một phần. ❌ C. Pentest: Test chạy, không phân tích code." },
    { q: "What is the role of a security auditor in security testing?", opts: ["Execute automated scripts", "Simulate attacks", "Review and analyze the system for security flaws", "Write test cases"], ans: 2, exp: "✅ C. Review and analyze for security flaws: Đúng - Security Auditor ĐÁNH GIÁ và PHÂN TÍCH hệ thống tìm lỗ hổng bảo mật. ❌ A. Scripts: Automation engineer. ❌ B. Simulate attacks: Penetration tester. ❌ D. Write test cases: Tester." },
    { q: "What is the purpose of a security risk assessment?", opts: ["Identify potential security threats and their impact", "Measure usability", "Create performance benchmarks", "Assess technical support availability"], ans: 0, exp: "✅ A. Identify threats and impact: Đúng - Security Risk Assessment NHẬN DIỆN các mối đe dọa và ĐÁNH GIÁ tác động. ❌ B. Usability: UX. ❌ C. Performance benchmarks: NFT. ❌ D. Technical support: Không liên quan." },
    { q: "What does the term 'XSS' stand for?", opts: ["XML Security Standard", "Cross-Site Scripting", "External System Security", "Xtra Security Services"], ans: 1, exp: "✅ B. Cross-Site Scripting: Đúng - XSS = Cross-Site Scripting, lỗ hổng cho phép inject malicious scripts vào web pages. ❌ A, C, D đều sai định nghĩa." },
    { q: "In Security Testing, what does 'Denial of Service (DoS)' refer to?", opts: ["Malware installation", "Overloading a system to make it unavailable", "Cross-site scripting", "Unauthorized access"], ans: 1, exp: "✅ B. Overloading system to make unavailable: Đúng - DoS attack LÀM QUÁ TẢI hệ thống khiến người dùng không thể truy cập. ❌ A. Malware: Khác loại attack. ❌ C. XSS: Khác. ❌ D. Unauthorized access: Authentication bypass." },
    { q: "Which is a common vulnerability that security testing aims to detect?", opts: ["UI layout issues", "Software design patterns", "Code comments", "SQL injection"], ans: 3, exp: "✅ D. SQL injection: Đúng - SQL Injection là LỖ HỔNG PHỔ BIẾN nhất mà security testing cần phát hiện. ❌ A. UI layout: GUI bugs. ❌ B. Design patterns: Không phải vulnerability. ❌ C. Comments: Không phải vulnerability." },
    { q: "Which of the following is NOT a type of security testing?", opts: ["Load testing", "Penetration testing", "Authentication testing", "Security auditing"], ans: 0, exp: "✅ A. Load testing - KHÔNG PHẢI security testing: Load testing là PERFORMANCE testing, không phải security. ❌ B, C, D đều là các loại security testing." },
    { q: "Which SDLC phase is most appropriate for conducting security testing?", opts: ["Coding", "Requirements gathering", "Maintenance", "Testing"], ans: 3, exp: "✅ D. Testing phase: Đúng - Security testing thường được thực hiện chính trong TESTING PHASE (dù có thể làm sớm hơn). ❌ A. Coding: Code review có thể, nhưng testing chính ở phase Testing. ❌ B, C: Không phải phases chính." },
    { q: "What is the primary goal of security testing?", opts: ["Uncover vulnerabilities and weaknesses", "Identify performance bottlenecks", "Ensure user-friendliness", "Validate code correctness"], ans: 0, exp: "✅ A. Uncover vulnerabilities and weaknesses: Đúng - Mục tiêu chính là PHÁT HIỆN LỖ HỔNG và điểm yếu bảo mật. ❌ B. Performance: NFT. ❌ C. User-friendliness: Usability. ❌ D. Code correctness: Unit testing." }
];

// 17. API Testing (6 câu - Q22-27 section 5)
QUIZ_DATA.topics[16].questions = [
    { q: "Which HTTP status code indicates a successful creation of a resource?", opts: ["200 OK", "201 Created", "404 Not Found", "500 Internal Server Error"], ans: 1, exp: "<b>✅ Đáp án đúng là B. 201 Created</b><br>201 là mã chuẩn khi một resource mới được tạo thành công (thường sau lệnh POST).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. 200:</b> Success chung chung.<br>❌ <b>C. 404:</b> Không tìm thấy.<br>❌ <b>D. 500:</b> Lỗi server." },
    { q: "Which status code means 'Unauthorized'?", opts: ["400", "401", "403", "500"], ans: 1, exp: "<b>✅ Đáp án đúng là B. 401</b><br>401 Unauthorized: Chưa đăng nhập hoặc token không hợp lệ (Identity unknown).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. 400:</b> Bad Request (Request sai format).<br>❌ <b>C. 403:</b> Forbidden (Đã đăng nhập nhưng không có quyền).<br>❌ <b>D. 500:</b> Server Error." },
    { q: "API testing mainly focuses on …", opts: ["GUI appearance", "Business logic layer", "Database triggers", "User experience"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Business logic layer</b><br>API (Application Programming Interface) là lớp logic nghiệp vụ kết nối Frontend và Database.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> Frontend/GUI.<br>❌ <b>C:</b> Database layer." },
    { q: "Which tool is widely used for API testing?", opts: ["Selenium", "Postman", "Appium", "TestLink"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Postman</b><br>Postman là tool phổ biến nhất để test REST/SOAP APIs.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C:</b> UI Automation.<br>❌ <b>D:</b> Test Management." },
    { q: "Which HTTP method is typically used to retrieve data?", opts: ["POST", "DELETE", "GET", "PUT"], ans: 2, exp: "<b>✅ Đáp án đúng là C. GET</b><br>GET dùng để LẤY dữ liệu (Read).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A. POST:</b> Tạo mới.<br>❌ <b>B. DELETE:</b> Xóa.<br>❌ <b>D. PUT:</b> Cập nhật." },
    { q: "A 500 status code indicates …", opts: ["Client error", "Successful request", "Redirection", "Server error"], ans: 3, exp: "<b>✅ Đáp án đúng là D. Server error</b><br>Các mã 5xx là lỗi phía Server (Internal Server Error, Bad Gateway...).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> 4xx.<br>❌ <b>B:</b> 2xx.<br>❌ <b>C:</b> 3xx." }
];

// 18. Database Testing (4 câu - Q28-31 section 5)
QUIZ_DATA.topics[17].questions = [
    { q: "Database testing primarily verifies …", opts: ["User interface design", "Data integrity and consistency", "Network speed", "Browser compatibility"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Data integrity and consistency</b><br>Trọng tâm của DB Testing là ĐÚNG DỮ LIỆU (Integrity) và NHẤT QUÁN (Consistency) qua các transaction.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> GUI/Frontend.<br>❌ <b>C:</b> Network." },
    { q: "Which SQL command is used to retrieve data from a database?", opts: ["INSERT", "DELETE", "SELECT", "UPDATE"], ans: 2, exp: "<b>✅ Đáp án đúng là C. SELECT</b><br>SQL cơ bản: SELECT để query dữ liệu.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B, D:</b> Để thay đổi dữ liệu (Write)." },
    { q: "Testing if a primary key accepts null values is checking for …", opts: ["Integrity constraint", "Performance", "Usability", "Security"], ans: 0, exp: "<b>✅ Đáp án đúng là A. Integrity constraint</b><br>Luật 'Primary Key không được Null' là một ràng buộc toàn vẹn (Integrity Constraint).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>B, C, D:</b> Các loại test khác." },
    { q: "Which tool is helpful for database unit testing?", opts: ["Selenium", "DBUnit", "JMeter", "Appium"], ans: 1, exp: "<b>✅ Đáp án đúng là B. DBUnit</b><br>DBUnit là tool (ext của JUnit) giúp đưa DB về trạng thái known state để test.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, D:</b> UI Test.<br>❌ <b>C:</b> Performance Test." }
];

// 19. White Box Testing (3 câu - Q32-34 section 5)
QUIZ_DATA.topics[18].questions = [
    { q: "Statement coverage ensures that …", opts: ["Every path is executed", "Every decision is executed", "Every line of code is executed at least once", "Every method is called"], ans: 2, exp: "<b>✅ Đáp án đúng là C. Every line of code is executed at least once</b><br>Statement Coverage đo lường số dòng code đã được chạy. Mục tiêu là không để sót dòng code chết (dead code).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Path coverage.<br>❌ <b>B:</b> Decision/Branch coverage.<br>❌ <b>D:</b> Method coverage." },
    { q: "White-box testing is also known as …", opts: ["Black-box testing", "Glass-box testing", "Functional testing", "Specification-based testing"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Glass-box testing</b><br>White-box (Hộp trắng) còn gọi là Glass-box (Hộp thủy tinh), Clear-box, Structural testing... ý nói có thể NHÌN THẤY bên trong.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, C, D:</b> Các khái niệm đối lập hoặc khác loại." },
    { q: "Which coverage is stronger?", opts: ["Statement coverage", "Decision (Branch) coverage", "They are equal", "Cannot compare"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Decision (Branch) coverage</b><br>Branch Coverage MẠNH HƠN vì nó cover cả nhánh True và False (Statements có thể chỉ cover 1 nhánh). Nếu đạt 100% Branch Coverage -> Chắc chắn đạt 100% Statement Coverage (nhưng ngược lại thì không)." }
];

// 20. Automation Testing (3 câu - Q35-37 section 5)
QUIZ_DATA.topics[19].questions = [
    { q: "Which test cases are best suited for automation?", opts: ["Test cases run once", "Ad-hoc test cases", "Regression testing and repetitive tasks", "Usability test cases"], ans: 2, exp: "<b>✅ Đáp án đúng là C. Regression testing and repetitive tasks</b><br>Automation hiệu quả nhất cho các task LẶP ĐI LẶP LẠI (Repetitive) và HỒI QUY (Regression) để tiết kiệm sức người.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A, B:</b> Test 1 lần thì manual nhanh hơn.<br>❌ <b>D:</b> Usability cần cảm nhận con người." },
    { q: "Common tool for web automation is:", opts: ["Jira", "Selenium", "Git", "Jenkins"], ans: 1, exp: "<b>✅ Đáp án đúng là B. Selenium</b><br>Selenium là 'King' trong mảng Web Automation (Open source).<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Bug tracking.<br>❌ <b>C:</b> Version control.<br>❌ <b>D:</b> CI/CD." },
    { q: "The main benefit of automation testing is …", opts: ["It replaces manual testers entirely", "It finds significantly more bugs than manual", "It saves time and cost in the long run", "It requires no programming skills"], ans: 2, exp: "<b>✅ Đáp án đúng là C. Saves time and cost in the long run</b><br>Lợi ích lớn nhất: Tốc độ và Doanh thu dài hạn (ROI). Test nhanh hơn, chạy đêm được.<br><br><b>Tại sao các đáp án khác sai?</b><br>❌ <b>A:</b> Không thể thay thế hoàn toàn manual (exploratory, usability).<br>❌ <b>B:</b> Manual tìm bug mới tốt hơn.<br>❌ <b>D:</b> Đa số cần coding skill." }
];
